# Generated by Django 3.2.9 on 2021-11-14 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_start_date', models.DateTimeField()),
                ('publish_end_date', models.DateTimeField()),
                ('lastupdate_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('escalate_date', models.DateTimeField()),
                ('subject', models.TextField()),
                ('detail', models.TextField()),
                ('history', models.TextField()),
                ('delay_code', models.CharField(max_length=2)),
                ('delay_reason', models.CharField(max_length=400)),
                ('alert_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InformationArcicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_start_date', models.DateTimeField()),
                ('publish_end_date', models.DateTimeField()),
                ('lastupdate_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.TextField()),
                ('detail', models.TextField()),
                ('history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InquiryArcicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_start_date', models.DateTimeField()),
                ('publish_end_date', models.DateTimeField()),
                ('lastupdate_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('escalate_date', models.DateTimeField()),
                ('subject', models.TextField()),
                ('detail', models.TextField()),
                ('history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OffmonitorArcicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_start_date', models.DateTimeField()),
                ('publish_end_date', models.DateTimeField()),
                ('lastupdate_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.TextField()),
                ('detail', models.TextField()),
                ('history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestArcicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_start_date', models.DateTimeField()),
                ('publish_end_date', models.DateTimeField()),
                ('lastupdate_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('escalate_date', models.DateTimeField()),
                ('subject', models.TextField()),
                ('detail', models.TextField()),
                ('history', models.TextField()),
            ],
        ),
    ]
